version: "3.9"

services:

  mongo:
    image: mongo:7

    container_name: mongo-db

    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    networks:
      - fiware

  orion:
    image: fiware/orion:4.5.0

    container_name: silvester-orion

    depends_on:
      - mongo

    ports:
      - "1026:1026"

    command:
      - -dbURI
      - mongodb://mongo:27017/orion

    networks:
      - fiware

  node:
    build:
      context: ./node

    container_name: silvester-node

    depends_on:
      - orion

    environment:

      ORION_URL=http://orion:1026
    ports:
      - "3000:3000"

    networks:
      - fiware

  angular:

    build:
      context: ./angular

    container_name: silvester-angular

    depends_on:
      - node

    environment:

      API_URL=http://node:3000

    ports:
      - "8080:80"

    networks:
      - fiware

volumes:
  mongo-data:

networks:
  fiware: