services:

####################################################
# ORION
####################################################

- type: web
  name: protodia-orion

  runtime: docker

  dockerContext: ./orion

  dockerfilePath: ./orion/Dockerfile

  envVars:
    - key: ORION_MONGO_URI
      sync: false

    - key: ORION_LOG_LEVEL
      value: DEBUG

####################################################
# NODE
####################################################

- type: web
  name: protodia-node

  runtime: docker

  dockerContext: ./node

  dockerfilePath: ./node/Dockerfile

  envVars:

  - key: ORION_URL
    value: https://protodia-orion.onrender.com

####################################################
# ANGULAR
####################################################

- type: web
  name: protodia-angular

  runtime: docker

  dockerContext: ./angular

  dockerfilePath: ./angular/Dockerfile

  envVars:

  - key: API_URL
    value: https://protodia-node.onrender.com