@host = http://localhost:1026/v2

## Subscriptions

### GET
GET {{host}}/subscriptions

### DELETE
@subscriptionId = 6837137b1d9f4eb18c097bfb
DELETE {{host}}/subscriptions/{{subscriptionId}}

## Entities

### GET
GET {{host}}/entities

### UPDATE
@entity = WeatherObserved:0001
PATCH {{host}}/entities/{{entity}}/attrs
Content-Type: application/json

{
  "clouds": {
    "value": 33,
    "type": "Float"
  }
}