@host = http://localhost:1026/v2
@subscriptionId = 68ca9ff9b89ffff9f6028daa

## Subscriptions

### GET
GET {{host}}/subscriptions

### POST
POST {{host}}/subscriptions
Content-Type: application/json

{
  "description": "Notify me when any attribute changes",
  "subject": {
    "entities": [
      {
        "id": "WeatherObserved:0001",
        "type": "WeatherObserved"
      }
    ],
    "condition": {
      "attrs": [
        "clouds",
        "dew_point",
        "dt",
        "feels_like",
        "humidity",
        "pressure",
        "sunrise",
        "sunset",
        "temp",
        "location",
        "timezone",
        "timezone_offset",
        "uvi",
        "visibility",
        "wind_deg",
        "wind_speed"
      ]
    }
  },
  "notification": {
    "http": {
      "url": "http://host.docker.internal:3000/notify"
    },
    "attrs": [
      "clouds",
      "dew_point",
      "dt",
      "feels_like",
      "humidity",
      "pressure",
      "sunrise",
      "sunset",
      "temp",
      "location",
      "timezone",
      "timezone_offset",
      "uvi",
      "visibility",
      "wind_deg",
      "wind_speed"
    ]
  },
  "expires": "2025-12-31T23:59:59.00Z",
  "throttling": 5
}


### DELETE
DELETE {{host}}/subscriptions/{{subscriptionId}}