@host = http://localhost:1026/v2
@entity = WeatherObserved:0001

### GET
GET {{host}}/entities

### UPDATE
PATCH {{host}}/entities/{{entity}}/attrs
Content-Type: application/json

{
  "clouds": {
    "value": 11,
    "type": "Integer"
  }
}

### DELETE
DELETE {{host}}/entities/{{entity}}