@host = http://localhost:1026/v2
@entity = WeatherObserved:0001

### GET
GET {{host}}/entities

### UPDATE WEATHER
PATCH {{host}}/entities/{{entity}}/attrs
Content-Type: application/json

{
  "clouds": {
    "value": 33,
    "type": "Integer"
  }
}

### UPDATE LOCATION
PATCH {{host}}/entities/{{entity}}/attrs
Content-Type: application/json

{
  "location": {
    "type": "Location",
    "value": {
      "lat": -5.795,
      "lng": -35.209
    }
  }
}

### DELETE
DELETE {{host}}/entities/{{entity}}